ExchangeRates/ExchangeRates.Web/Models/ExchangeRatesPeriod.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using ExchangeRates.Infrastructure.Models;
using ExchangeRates.Infrastructure.Services;
using ExchangeRates.Web.Models.Validators;

namespace ExchangeRates.Web.Models
{
    public class ExchangeRatesPeriod
    {
        private readonly ExchangeRatesService _exchangeRatesService;
        private Currency _baseCurrency;
        private Currency[] _currencies;

        public Currency BaseCurrency
        {
            get { return _baseCurrency ?? (_baseCurrency = _exchangeRatesService.GetCurrencyByShortName("USD")); }
        }

        public Currency[] Currencies
        {
            get
            {
                return _currencies ?? (_currencies = _exchangeRatesService.GetCurrenciesExceptBase(BaseCurrency.ShortName).ToArray());
            }
        }

        [Required]
        [StartDateValidator]
        public DateTime StartDate { get; set; }

        [Required]
        [EndDateValidator]
        public DateTime EndDate { get; set; }

        [Required]
        public int CurrencyId { get; set; }

        public ExchangeRatesPeriod()
        {
            _exchangeRatesService = new ExchangeRatesService();
            EndDate = DateTime.UtcNow;
            StartDate = EndDate.AddMonths(-2);
        }
    }
}

ExchangeRates/ExchangeRates.Web/Models/Validators/EndDateValidator.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace ExchangeRates.Web.Models.Validators
{
    public class EndDateValidator : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            var exchangeRatesPeriod = validationContext.ObjectInstance as ExchangeRatesPeriod;
            if (exchangeRatesPeriod == null)
            {
                throw new EntityException("ExchangeRatesPeriod instance not found");
            }
            if (exchangeRatesPeriod.EndDate > DateTime.UtcNow)
            {
                return new ValidationResult("End date should not exceed current date");
            }
            return ValidationResult.Success;
        }
    }
}

ExchangeRates/ExchangeRates.Web/Models/Validators/StartDateValidator.cs
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace ExchangeRates.Web.Models.Validators
{
    public class StartDateValidator : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            var exchangeRatesPeriod = validationContext.ObjectInstance as ExchangeRatesPeriod;
            if (exchangeRatesPeriod == null)
            {
                throw new EntityException("ExchangeRatesPeriod instance not found");
            }
            if (exchangeRatesPeriod.StartDate > exchangeRatesPeriod.EndDate)
            {
                return new ValidationResult("Start date should not exceed end date");
            }
            if (exchangeRatesPeriod.StartDate.AddMonths(2) < exchangeRatesPeriod.EndDate)
            {
                return new ValidationResult("Date period should not exceed two months, increase date");
            }
            return ValidationResult.Success;
        }
    }
}

ExchangeRates/ExchangeRates.Web/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ExchangeRates.Infrastructure.Models;
using ExchangeRates.Infrastructure.Services;
using ExchangeRates.Web.Models;

namespace ExchangeRates.Web.Controllers
{
    public class IndexController : Controller
    {
        private readonly ExchangeRatesService _exchangeRatesService;

        public IndexController()
        {
            _exchangeRatesService = new ExchangeRatesService();
        }

        public ActionResult Index()
        {
            return View(new ExchangeRatesPeriod());
        }

        [HttpPost]
        public JsonResult UpdateRates(ExchangeRatesPeriod model)
        {
            if (ModelState.IsValid)
            {
                CurrencyRate[] rates;
                
                try
                {
                    rates = _exchangeRatesService.GetCurrencyRates(model.BaseCurrency.Id, model.CurrencyId,
                                                                   model.StartDate, model.EndDate).ToArray();
                }
                catch (Exception)
                {
                    return Json(new { success = false, error = "A server error has occursed."});
                }
                
                return Json(new
                    {
                            success = true,
                            rates = rates.Select(it => new
                                {
                                        date = it.Date.ToString("yyyy-MM-dd"),
                                        rate = it.Rate
                                })
                    });
            }
            return Json(new { success = false, error = "Fix validation errors", validationErrors = GetErrorsFromModelState() });
        }

        private IEnumerable<dynamic> GetErrorsFromModelState()
        {
            // get error messages of data annatation validation attributes
            return ModelState
                    .Select(it => new
                    {
                        Field = it.Key,
                        ErrorMessages = it.Value.Errors.Select(that => that.ErrorMessage).ToArray()
                    })
                    .Where(it => it.ErrorMessages.Length > 0)
                    .ToArray();
        }
    }
}

ExchangeRates/ExchangeRates.Web/Views/Index/Index.cshtml
@model ExchangeRates.Web.Models.ExchangeRatesPeriod
<style>
    #update-rates-button-container {
        margin-top: 10px;
        margin-bottom: 10px;
        text-align: center;
    }
</style>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<div id="exchange-rates" class="container">
    <div id="form" class="row">
        @using (Ajax.BeginForm("UpdateRates", "Index", null, new AjaxOptions { OnSuccess = "exchangeRatesViewModel.onUpdateRatesSuccess" }, new { id = "update-rates-form", @class = "form-inline" }))
        {
            <div class="span12">
                <div class="row">
                    <div class="control-group span4" data-bind="css: { error: startDateErrorMessage() }">
                        <label class="control-label" for="start-date">Start date</label>
                        <div class="controls">
                            @Html.TextBoxFor(m => m.StartDate, "{0:d}", new { id = "start-date", @class = "input-block-level date" })
                            <span class="help-inline" data-bind="visible: startDateErrorMessage(), text: startDateErrorMessage"></span>
                        </div>
                    </div>

                    <div class="control-group span4" data-bind="css: { error: endDateErrorMessage() }">
                        <label class="control-label" for="end-date">End date</label>
                        <div class="controls">
                            @Html.TextBoxFor(m => m.EndDate, "{0:d}", new { id = "end-date", @class = "input-block-level date" })
                            <span class="help-inline" data-bind="visible: endDateErrorMessage(), text: endDateErrorMessage"></span>
                        </div>
                    </div>

                    <div class="control-group span4">
                        <label class="control-label" for="currency">Currency</label>
                        <div class="controls">
                            @Html.DropDownListFor(m => m.CurrencyId, new SelectList(Model.Currencies, "Id", "ShortName"), new { id = "currency", @class = "input-block-level" })
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="span12">
                <div id="update-rates-button-container" class="row">
                    
                    <a id="update-rates-button" class="btn btn-large btn-primary" data-bind="click: updateRates"><img src="~/Content/images/ajax-loader.gif" data-bind="visible: isUpdating"/> <span data-bind="text: updateButtonText"></span></a>
                </div>
            </div>
        }
    </div>
    <div id="chart-container" class="row" data-bind="visible: hasData() && !errorMessage().length">
        <div class="span12">
            <div id="chart" style="min-width: 400px; height: 400px; margin: 0 auto"></div>
        </div>
    </div>

    <div class="row">
        <div class="span12">
            <div class="alert alert-error" data-bind="visible: errorMessage().length">
                <span data-bind="text: errorMessage"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="span12">
            <div class="alert alert-info" data-bind="visible: !hasData() && !errorMessage().length">
                No data for selected period
            </div>
        </div>
    </div>

    
</div>

<script>
    var exchangeRatesViewModel = {};
    
    $(function() {
        $("input:text.date").datepicker({nextText: '', prevText: ''});
        exchangeRatesViewModel = new ExchangeRatesViewModel();
        ko.applyBindings(exchangeRatesViewModel, document.getElementById("exchange-rates"));
    });

    function ExchangeRatesViewModel() {
        var self = this,
            updateRatesButtonText = "Update rates",
            updatingRatesButtonText = "Updating rates...";

        this.hasData = ko.observable(true);

        this.startDateErrorMessage = ko.observable("");
        this.endDateErrorMessage = ko.observable("");

        this.errorMessage = ko.observable("");

        this.isUpdating = ko.observable(false);
        this.updateButtonText = ko.observable(updateRatesButtonText);

        this.updateRates = function () {
            if (!self.isUpdating()) {
                self.isUpdating(true);
                self.updateButtonText(updatingRatesButtonText);
                $("#update-rates-form").submit();
            }
        };

        this.onUpdateRatesSuccess = function (data) {
            self.isUpdating(false);
            self.updateButtonText(updateRatesButtonText);
            var i = 0;
            // clear error messages
            self.startDateErrorMessage("");
            self.endDateErrorMessage("");
            self.errorMessage("");
            if (data && data.success && data.rates) {

                self.hasData(data.rates.length);

                // construct data values for the chart
                var rates = [];
                for (i = 0; i < data.rates.length; i++) {
                    var rate = data.rates[i];
                    var chartValue = [new Date(rate.date + "T00:00:00Z").getTime(), rate.rate];
                    rates.push(chartValue);
                }

                // show data on the chart
                $('#chart').highcharts({
                    chart: {
                        type: 'line',
                    },
                    title: {
                        text: ''
                    },
                    subtitle: {
                        text: ''
                    },
                    xAxis: {
                        type: 'datetime',
                        minTickInterval: 3600000 * 24
                    },
                    tooltip: {
                        formatter: function () {
                            return $.datepicker.formatDate('DD, MM d, yy', new Date(this.x)) +
                                '<br><b>' + Highcharts.numberFormat(this.y, 2) + '</b>';
                        },
                        valueDecimals: 2,
                    },
                    yAxis: {
                        title: ''
                    },
                    legend: {
                        enabled: false
                    },
                    exporting: {
                        enabled: false
                    },
                    series: [{
                        name: '',
                        data: rates,
                    }]
                });
            } else {
                self.hasData(false);

                // if there is error message
                if (data.error) {
                    self.errorMessage(data.error);
                }

                // if there are some validation errors
                if (data.validationErrors && data.validationErrors.length) {
                    // iterate through them and set corresponding observable fileds
                    for (i = 0; i < data.validationErrors.length; i++) {
                        var error = data.validationErrors[i];
                        if (error.Field === "StartDate") {
                            self.startDateErrorMessage(error.ErrorMessages.join(". "));
                        }
                        else if (error.Field === "EndDate") {
                            self.endDateErrorMessage(error.ErrorMessages.join(". "));
                        }
                    }
                }
            }
        };
    }
</script>

ExchangeRates/ExchangeRates.Web/Views/_Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Exchange Rates</title>
    @Styles.Render("~/Styles")
    @Scripts.Render("~/Scripts")
    <style>
        #body {
            margin-top: 60px;
        }
    </style>
</head>
    <body>
        <div id="menu">
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="brand" href="/">Exchange rates</a>
                    </div>
                </div>
            </div>
        </div>
        <div id="body">
        
            @RenderBody()
        </div>
    </body>
</html>